# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geoSUIT.ui'
#
# Created: Wed Aug 03 18:40:17 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setEnabled(True)
        Dialog.resize(693, 657)
        Dialog.setMaximumSize(QtCore.QSize(694, 700))
        font = QtGui.QFont()
        font.setPointSize(6)
        Dialog.setFont(font)
        Dialog.setAcceptDrops(True)
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(False)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.toolBox = QtGui.QToolBox(Dialog)
        self.toolBox.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.toolBox.setFont(font)
        self.toolBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolBox.setStyleSheet(_fromUtf8("\n"
"font: 75 italic 10pt \"MS Shell Dlg 2\";"))
        self.toolBox.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtGui.QFrame.Plain)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 675, 459))
        self.page.setObjectName(_fromUtf8("page"))
        self.OutGBox = QtGui.QGroupBox(self.page)
        self.OutGBox.setGeometry(QtCore.QRect(0, 70, 661, 60))
        self.OutGBox.setObjectName(_fromUtf8("OutGBox"))
        self.OutlEdt = QtGui.QLineEdit(self.OutGBox)
        self.OutlEdt.setGeometry(QtCore.QRect(40, 30, 601, 20))
        self.OutlEdt.setObjectName(_fromUtf8("OutlEdt"))
        self.RetriveFileTBtn = QtGui.QToolButton(self.OutGBox)
        self.RetriveFileTBtn.setGeometry(QtCore.QRect(10, 30, 25, 21))
        self.RetriveFileTBtn.setObjectName(_fromUtf8("RetriveFileTBtn"))
        self.LblLogo = QtGui.QLabel(self.page)
        self.LblLogo.setGeometry(QtCore.QRect(229, 269, 241, 181))
        self.LblLogo.setText(_fromUtf8(""))
        self.LblLogo.setScaledContents(True)
        self.LblLogo.setObjectName(_fromUtf8("LblLogo"))
        self.groupBox = QtGui.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(0, 140, 571, 131))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.settingCheckBox = QtGui.QCheckBox(self.groupBox)
        self.settingCheckBox.setGeometry(QtCore.QRect(20, 30, 221, 21))
        self.settingCheckBox.setChecked(True)
        self.settingCheckBox.setObjectName(_fromUtf8("settingCheckBox"))
        self.prefixECOlEdt = QtGui.QLineEdit(self.groupBox)
        self.prefixECOlEdt.setGeometry(QtCore.QRect(490, 69, 53, 22))
        self.prefixECOlEdt.setObjectName(_fromUtf8("prefixECOlEdt"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(309, 73, 161, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(308, 46, 161, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.preFIXcheckBox = QtGui.QCheckBox(self.groupBox)
        self.preFIXcheckBox.setGeometry(QtCore.QRect(310, 10, 171, 20))
        self.preFIXcheckBox.setChecked(True)
        self.preFIXcheckBox.setObjectName(_fromUtf8("preFIXcheckBox"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(310, 100, 161, 22))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.prefixSOClEdt = QtGui.QLineEdit(self.groupBox)
        self.prefixSOClEdt.setGeometry(QtCore.QRect(490, 100, 54, 22))
        self.prefixSOClEdt.setObjectName(_fromUtf8("prefixSOClEdt"))
        self.prefixENVlEdt = QtGui.QLineEdit(self.groupBox)
        self.prefixENVlEdt.setGeometry(QtCore.QRect(490, 40, 53, 22))
        self.prefixENVlEdt.setObjectName(_fromUtf8("prefixENVlEdt"))
        self.groupBox_2 = QtGui.QGroupBox(self.page)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 661, 60))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.BaseLayerLbl = QtGui.QLabel(self.groupBox_2)
        self.BaseLayerLbl.setGeometry(QtCore.QRect(10, 30, 641, 16))
        self.BaseLayerLbl.setObjectName(_fromUtf8("BaseLayerLbl"))
        self.SetBtnHelp = QtGui.QPushButton(self.page)
        self.SetBtnHelp.setGeometry(QtCore.QRect(581, 211, 72, 24))
        self.SetBtnHelp.setMaximumSize(QtCore.QSize(72, 24))
        self.SetBtnHelp.setObjectName(_fromUtf8("SetBtnHelp"))
        self.SetBtnAbout = QtGui.QPushButton(self.page)
        self.SetBtnAbout.setGeometry(QtCore.QRect(581, 241, 72, 24))
        self.SetBtnAbout.setMaximumSize(QtCore.QSize(72, 24))
        self.SetBtnAbout.setObjectName(_fromUtf8("SetBtnAbout"))
        self.SetBtnBox = QtGui.QDialogButtonBox(self.page)
        self.SetBtnBox.setGeometry(QtCore.QRect(581, 151, 71, 56))
        self.SetBtnBox.setMaximumSize(QtCore.QSize(71, 114))
        self.SetBtnBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SetBtnBox.setOrientation(QtCore.Qt.Vertical)
        self.SetBtnBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.SetBtnBox.setCenterButtons(True)
        self.SetBtnBox.setObjectName(_fromUtf8("SetBtnBox"))
        self.LoadProgressBar = QtGui.QProgressBar(self.page)
        self.LoadProgressBar.setGeometry(QtCore.QRect(0, 430, 191, 21))
        self.LoadProgressBar.setProperty("value", 0)
        self.LoadProgressBar.setObjectName(_fromUtf8("LoadProgressBar"))
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.EnvironmentaleQTbox = QtGui.QWidget()
        self.EnvironmentaleQTbox.setGeometry(QtCore.QRect(0, 0, 675, 459))
        self.EnvironmentaleQTbox.setObjectName(_fromUtf8("EnvironmentaleQTbox"))
        self.EnvlistFieldsCBox = QtGui.QComboBox(self.EnvironmentaleQTbox)
        self.EnvlistFieldsCBox.setGeometry(QtCore.QRect(88, 62, 364, 22))
        self.EnvlistFieldsCBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.EnvlistFieldsCBox.setObjectName(_fromUtf8("EnvlistFieldsCBox"))
        self.EnvLbl = QtGui.QLabel(self.EnvironmentaleQTbox)
        self.EnvLbl.setGeometry(QtCore.QRect(9, 9, 51, 16))
        self.EnvLbl.setObjectName(_fromUtf8("EnvLbl"))
        self.EnvMapNameLbl = QtGui.QLabel(self.EnvironmentaleQTbox)
        self.EnvMapNameLbl.setGeometry(QtCore.QRect(69, 8, 431, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.EnvMapNameLbl.setFont(font)
        self.EnvMapNameLbl.setTextFormat(QtCore.Qt.AutoText)
        self.EnvMapNameLbl.setObjectName(_fromUtf8("EnvMapNameLbl"))
        self.EnvTEdit = QtGui.QTextEdit(self.EnvironmentaleQTbox)
        self.EnvTEdit.setGeometry(QtCore.QRect(10, 420, 531, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.EnvTEdit.sizePolicy().hasHeightForWidth())
        self.EnvTEdit.setSizePolicy(sizePolicy)
        self.EnvTEdit.setObjectName(_fromUtf8("EnvTEdit"))
        self.EnvFieldsLbl = QtGui.QLabel(self.EnvironmentaleQTbox)
        self.EnvFieldsLbl.setGeometry(QtCore.QRect(9, 62, 34, 16))
        self.EnvFieldsLbl.setObjectName(_fromUtf8("EnvFieldsLbl"))
        self.EnvHelpBtn = QtGui.QPushButton(self.EnvironmentaleQTbox)
        self.EnvHelpBtn.setGeometry(QtCore.QRect(560, 420, 102, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvHelpBtn.sizePolicy().hasHeightForWidth())
        self.EnvHelpBtn.setSizePolicy(sizePolicy)
        self.EnvHelpBtn.setMaximumSize(QtCore.QSize(110, 16777215))
        self.EnvHelpBtn.setObjectName(_fromUtf8("EnvHelpBtn"))
        self.line_2 = QtGui.QFrame(self.EnvironmentaleQTbox)
        self.line_2.setGeometry(QtCore.QRect(9, 36, 657, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_4 = QtGui.QFrame(self.EnvironmentaleQTbox)
        self.line_4.setGeometry(QtCore.QRect(10, 400, 660, 15))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.EnvTabWidget = QtGui.QTabWidget(self.EnvironmentaleQTbox)
        self.EnvTabWidget.setGeometry(QtCore.QRect(14, 105, 655, 281))
        self.EnvTabWidget.setObjectName(_fromUtf8("EnvTabWidget"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.EnvWeighTableWidget = QtGui.QTableWidget(self.tab_5)
        self.EnvWeighTableWidget.setGeometry(QtCore.QRect(10, 11, 630, 191))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvWeighTableWidget.sizePolicy().hasHeightForWidth())
        self.EnvWeighTableWidget.setSizePolicy(sizePolicy)
        self.EnvWeighTableWidget.setAcceptDrops(False)
        self.EnvWeighTableWidget.setDragEnabled(True)
        self.EnvWeighTableWidget.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.EnvWeighTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.EnvWeighTableWidget.setRowCount(0)
        self.EnvWeighTableWidget.setObjectName(_fromUtf8("EnvWeighTableWidget"))
        self.EnvWeighTableWidget.setColumnCount(0)
        self.EnvWeighTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.EnvWeighTableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.EnvWeighTableWidget.verticalHeader().setHighlightSections(True)
        self.EnvGetWeightBtn = QtGui.QPushButton(self.tab_5)
        self.EnvGetWeightBtn.setGeometry(QtCore.QRect(540, 220, 104, 24))
        self.EnvGetWeightBtn.setMaximumSize(QtCore.QSize(104, 16777215))
        self.EnvGetWeightBtn.setObjectName(_fromUtf8("EnvGetWeightBtn"))
        self.EnvProgressBar = QtGui.QProgressBar(self.tab_5)
        self.EnvProgressBar.setGeometry(QtCore.QRect(160, 220, 371, 25))
        self.EnvProgressBar.setProperty("value", 0)
        self.EnvProgressBar.setObjectName(_fromUtf8("EnvProgressBar"))
        self.EnvSaveCfgBtn = QtGui.QPushButton(self.tab_5)
        self.EnvSaveCfgBtn.setGeometry(QtCore.QRect(10, 220, 104, 24))
        self.EnvSaveCfgBtn.setObjectName(_fromUtf8("EnvSaveCfgBtn"))
        self.EnvTabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.EnvCalculateBtn = QtGui.QPushButton(self.tab_6)
        self.EnvCalculateBtn.setGeometry(QtCore.QRect(530, 210, 110, 24))
        self.EnvCalculateBtn.setMaximumSize(QtCore.QSize(111, 16777215))
        self.EnvCalculateBtn.setObjectName(_fromUtf8("EnvCalculateBtn"))
        self.EnvTableWidget = QtGui.QTableWidget(self.tab_6)
        self.EnvTableWidget.setEnabled(True)
        self.EnvTableWidget.setGeometry(QtCore.QRect(10, 15, 630, 181))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvTableWidget.sizePolicy().hasHeightForWidth())
        self.EnvTableWidget.setSizePolicy(sizePolicy)
        self.EnvTableWidget.setDragEnabled(True)
        self.EnvTableWidget.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.EnvTableWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.EnvTableWidget.setObjectName(_fromUtf8("EnvTableWidget"))
        self.EnvTableWidget.setColumnCount(0)
        self.EnvTableWidget.setRowCount(0)
        self.EnvTabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.line_3 = QtGui.QFrame(self.EnvironmentaleQTbox)
        self.line_3.setGeometry(QtCore.QRect(560, 58, 20, 32))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_6 = QtGui.QFrame(self.EnvironmentaleQTbox)
        self.line_6.setGeometry(QtCore.QRect(554, 58, 20, 32))
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.EnvRemoveFieldBtn = QtGui.QPushButton(self.EnvironmentaleQTbox)
        self.EnvRemoveFieldBtn.setGeometry(QtCore.QRect(590, 62, 72, 24))
        self.EnvRemoveFieldBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.EnvRemoveFieldBtn.setObjectName(_fromUtf8("EnvRemoveFieldBtn"))
        self.EnvAddFieldBtn = QtGui.QPushButton(self.EnvironmentaleQTbox)
        self.EnvAddFieldBtn.setGeometry(QtCore.QRect(465, 62, 72, 24))
        self.EnvAddFieldBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.EnvAddFieldBtn.setObjectName(_fromUtf8("EnvAddFieldBtn"))
        self.toolBox.addItem(self.EnvironmentaleQTbox, _fromUtf8(""))
        self.EconomicsQTBox = QtGui.QWidget()
        self.EconomicsQTBox.setGeometry(QtCore.QRect(0, 0, 675, 459))
        self.EconomicsQTBox.setObjectName(_fromUtf8("EconomicsQTBox"))
        self.EcolistFieldsCBox = QtGui.QComboBox(self.EconomicsQTBox)
        self.EcolistFieldsCBox.setGeometry(QtCore.QRect(88, 50, 364, 22))
        self.EcolistFieldsCBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.EcolistFieldsCBox.setObjectName(_fromUtf8("EcolistFieldsCBox"))
        self.EcoFieldsLbl = QtGui.QLabel(self.EconomicsQTBox)
        self.EcoFieldsLbl.setGeometry(QtCore.QRect(9, 50, 50, 16))
        self.EcoFieldsLbl.setObjectName(_fromUtf8("EcoFieldsLbl"))
        self.EcoLbl = QtGui.QLabel(self.EconomicsQTBox)
        self.EcoLbl.setGeometry(QtCore.QRect(10, 10, 51, 16))
        self.EcoLbl.setObjectName(_fromUtf8("EcoLbl"))
        self.EcoTEdit = QtGui.QTextEdit(self.EconomicsQTBox)
        self.EcoTEdit.setGeometry(QtCore.QRect(10, 420, 530, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.EcoTEdit.sizePolicy().hasHeightForWidth())
        self.EcoTEdit.setSizePolicy(sizePolicy)
        self.EcoTEdit.setObjectName(_fromUtf8("EcoTEdit"))
        self.EcoHelpBtn = QtGui.QPushButton(self.EconomicsQTBox)
        self.EcoHelpBtn.setGeometry(QtCore.QRect(560, 420, 99, 24))
        self.EcoHelpBtn.setObjectName(_fromUtf8("EcoHelpBtn"))
        self.EcoRemoveFieldBtn = QtGui.QPushButton(self.EconomicsQTBox)
        self.EcoRemoveFieldBtn.setGeometry(QtCore.QRect(590, 50, 72, 24))
        self.EcoRemoveFieldBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.EcoRemoveFieldBtn.setObjectName(_fromUtf8("EcoRemoveFieldBtn"))
        self.EcoAddFieldBtn = QtGui.QPushButton(self.EconomicsQTBox)
        self.EcoAddFieldBtn.setGeometry(QtCore.QRect(465, 49, 72, 24))
        self.EcoAddFieldBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.EcoAddFieldBtn.setObjectName(_fromUtf8("EcoAddFieldBtn"))
        self.EcoMapNameLbl = QtGui.QLabel(self.EconomicsQTBox)
        self.EcoMapNameLbl.setGeometry(QtCore.QRect(90, 9, 431, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.EcoMapNameLbl.setFont(font)
        self.EcoMapNameLbl.setTextFormat(QtCore.Qt.AutoText)
        self.EcoMapNameLbl.setObjectName(_fromUtf8("EcoMapNameLbl"))
        self.line_5 = QtGui.QFrame(self.EconomicsQTBox)
        self.line_5.setGeometry(QtCore.QRect(8, 25, 657, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_7 = QtGui.QFrame(self.EconomicsQTBox)
        self.line_7.setGeometry(QtCore.QRect(10, 400, 660, 15))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.EcoTabWidget = QtGui.QTabWidget(self.EconomicsQTBox)
        self.EcoTabWidget.setGeometry(QtCore.QRect(10, 90, 655, 301))
        self.EcoTabWidget.setObjectName(_fromUtf8("EcoTabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.EcoGetWeightBtn = QtGui.QPushButton(self.tab_3)
        self.EcoGetWeightBtn.setEnabled(True)
        self.EcoGetWeightBtn.setGeometry(QtCore.QRect(540, 238, 104, 24))
        self.EcoGetWeightBtn.setObjectName(_fromUtf8("EcoGetWeightBtn"))
        self.EcoWeighTableWidget = QtGui.QTableWidget(self.tab_3)
        self.EcoWeighTableWidget.setGeometry(QtCore.QRect(10, 11, 630, 211))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EcoWeighTableWidget.sizePolicy().hasHeightForWidth())
        self.EcoWeighTableWidget.setSizePolicy(sizePolicy)
        self.EcoWeighTableWidget.setDragEnabled(True)
        self.EcoWeighTableWidget.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.EcoWeighTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.EcoWeighTableWidget.setRowCount(0)
        self.EcoWeighTableWidget.setObjectName(_fromUtf8("EcoWeighTableWidget"))
        self.EcoWeighTableWidget.setColumnCount(0)
        self.EcoWeighTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.EcoWeighTableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.EcoWeighTableWidget.verticalHeader().setHighlightSections(True)
        self.EcoProgressBar = QtGui.QProgressBar(self.tab_3)
        self.EcoProgressBar.setGeometry(QtCore.QRect(160, 240, 371, 25))
        self.EcoProgressBar.setProperty("value", 0)
        self.EcoProgressBar.setObjectName(_fromUtf8("EcoProgressBar"))
        self.EcoSaveCfgBtn = QtGui.QPushButton(self.tab_3)
        self.EcoSaveCfgBtn.setGeometry(QtCore.QRect(10, 240, 104, 24))
        self.EcoSaveCfgBtn.setObjectName(_fromUtf8("EcoSaveCfgBtn"))
        self.EcoTabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.EcoTableWidget = QtGui.QTableWidget(self.tab_4)
        self.EcoTableWidget.setGeometry(QtCore.QRect(10, 15, 630, 211))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EcoTableWidget.sizePolicy().hasHeightForWidth())
        self.EcoTableWidget.setSizePolicy(sizePolicy)
        self.EcoTableWidget.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.EcoTableWidget.setDragEnabled(False)
        self.EcoTableWidget.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.EcoTableWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.EcoTableWidget.setObjectName(_fromUtf8("EcoTableWidget"))
        self.EcoTableWidget.setColumnCount(0)
        self.EcoTableWidget.setRowCount(0)
        self.EcoCalculateBtn = QtGui.QPushButton(self.tab_4)
        self.EcoCalculateBtn.setGeometry(QtCore.QRect(530, 240, 110, 24))
        self.EcoCalculateBtn.setObjectName(_fromUtf8("EcoCalculateBtn"))
        self.EcoTabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.line_8 = QtGui.QFrame(self.EconomicsQTBox)
        self.line_8.setGeometry(QtCore.QRect(550, 40, 20, 32))
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.line_9 = QtGui.QFrame(self.EconomicsQTBox)
        self.line_9.setGeometry(QtCore.QRect(560, 40, 20, 32))
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.toolBox.addItem(self.EconomicsQTBox, _fromUtf8(""))
        self.SocialQTBox = QtGui.QWidget()
        self.SocialQTBox.setGeometry(QtCore.QRect(0, 0, 675, 459))
        self.SocialQTBox.setObjectName(_fromUtf8("SocialQTBox"))
        self.SocTabWidget = QtGui.QTabWidget(self.SocialQTBox)
        self.SocTabWidget.setGeometry(QtCore.QRect(10, 90, 655, 291))
        self.SocTabWidget.setObjectName(_fromUtf8("SocTabWidget"))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.SocGetWeightBtn = QtGui.QPushButton(self.tab_7)
        self.SocGetWeightBtn.setEnabled(True)
        self.SocGetWeightBtn.setGeometry(QtCore.QRect(540, 220, 104, 24))
        self.SocGetWeightBtn.setObjectName(_fromUtf8("SocGetWeightBtn"))
        self.SocWeighTableWidget = QtGui.QTableWidget(self.tab_7)
        self.SocWeighTableWidget.setGeometry(QtCore.QRect(10, 10, 630, 191))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SocWeighTableWidget.sizePolicy().hasHeightForWidth())
        self.SocWeighTableWidget.setSizePolicy(sizePolicy)
        self.SocWeighTableWidget.setAcceptDrops(False)
        self.SocWeighTableWidget.setDragEnabled(True)
        self.SocWeighTableWidget.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.SocWeighTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.SocWeighTableWidget.setRowCount(0)
        self.SocWeighTableWidget.setObjectName(_fromUtf8("SocWeighTableWidget"))
        self.SocWeighTableWidget.setColumnCount(0)
        self.SocWeighTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.SocWeighTableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.SocWeighTableWidget.verticalHeader().setHighlightSections(True)
        self.SocProgressBar = QtGui.QProgressBar(self.tab_7)
        self.SocProgressBar.setGeometry(QtCore.QRect(160, 220, 371, 25))
        self.SocProgressBar.setProperty("value", 0)
        self.SocProgressBar.setObjectName(_fromUtf8("SocProgressBar"))
        self.SocSaveCfgBtn = QtGui.QPushButton(self.tab_7)
        self.SocSaveCfgBtn.setGeometry(QtCore.QRect(10, 220, 104, 24))
        self.SocSaveCfgBtn.setObjectName(_fromUtf8("SocSaveCfgBtn"))
        self.SocTabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.SocTableWidget = QtGui.QTableWidget(self.tab_8)
        self.SocTableWidget.setGeometry(QtCore.QRect(10, 15, 630, 191))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SocTableWidget.sizePolicy().hasHeightForWidth())
        self.SocTableWidget.setSizePolicy(sizePolicy)
        self.SocTableWidget.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.SocTableWidget.setDragEnabled(False)
        self.SocTableWidget.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.SocTableWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.SocTableWidget.setObjectName(_fromUtf8("SocTableWidget"))
        self.SocTableWidget.setColumnCount(0)
        self.SocTableWidget.setRowCount(0)
        self.SocCalculateBtn = QtGui.QPushButton(self.tab_8)
        self.SocCalculateBtn.setGeometry(QtCore.QRect(530, 220, 110, 24))
        self.SocCalculateBtn.setObjectName(_fromUtf8("SocCalculateBtn"))
        self.SocTabWidget.addTab(self.tab_8, _fromUtf8(""))
        self.SocAddFieldBtn = QtGui.QPushButton(self.SocialQTBox)
        self.SocAddFieldBtn.setGeometry(QtCore.QRect(465, 44, 72, 24))
        self.SocAddFieldBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.SocAddFieldBtn.setObjectName(_fromUtf8("SocAddFieldBtn"))
        self.SoclistFieldsCBox = QtGui.QComboBox(self.SocialQTBox)
        self.SoclistFieldsCBox.setGeometry(QtCore.QRect(88, 45, 364, 22))
        self.SoclistFieldsCBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.SoclistFieldsCBox.setObjectName(_fromUtf8("SoclistFieldsCBox"))
        self.line_10 = QtGui.QFrame(self.SocialQTBox)
        self.line_10.setGeometry(QtCore.QRect(562, 41, 20, 32))
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.SocRemoveFieldBtn = QtGui.QPushButton(self.SocialQTBox)
        self.SocRemoveFieldBtn.setGeometry(QtCore.QRect(590, 45, 72, 24))
        self.SocRemoveFieldBtn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.SocRemoveFieldBtn.setObjectName(_fromUtf8("SocRemoveFieldBtn"))
        self.SocFieldsLbl = QtGui.QLabel(self.SocialQTBox)
        self.SocFieldsLbl.setGeometry(QtCore.QRect(9, 45, 50, 16))
        self.SocFieldsLbl.setObjectName(_fromUtf8("SocFieldsLbl"))
        self.line_11 = QtGui.QFrame(self.SocialQTBox)
        self.line_11.setGeometry(QtCore.QRect(554, 41, 20, 32))
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.line_12 = QtGui.QFrame(self.SocialQTBox)
        self.line_12.setGeometry(QtCore.QRect(10, 400, 660, 15))
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.SocTEdit = QtGui.QTextEdit(self.SocialQTBox)
        self.SocTEdit.setGeometry(QtCore.QRect(10, 420, 530, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.SocTEdit.sizePolicy().hasHeightForWidth())
        self.SocTEdit.setSizePolicy(sizePolicy)
        self.SocTEdit.setObjectName(_fromUtf8("SocTEdit"))
        self.SocHelpBtn = QtGui.QPushButton(self.SocialQTBox)
        self.SocHelpBtn.setGeometry(QtCore.QRect(560, 420, 99, 24))
        self.SocHelpBtn.setObjectName(_fromUtf8("SocHelpBtn"))
        self.EcoLbl_2 = QtGui.QLabel(self.SocialQTBox)
        self.EcoLbl_2.setGeometry(QtCore.QRect(6, 2, 51, 16))
        self.EcoLbl_2.setObjectName(_fromUtf8("EcoLbl_2"))
        self.SocMapNameLbl = QtGui.QLabel(self.SocialQTBox)
        self.SocMapNameLbl.setGeometry(QtCore.QRect(88, 6, 431, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.SocMapNameLbl.setFont(font)
        self.SocMapNameLbl.setTextFormat(QtCore.Qt.AutoText)
        self.SocMapNameLbl.setObjectName(_fromUtf8("SocMapNameLbl"))
        self.line_13 = QtGui.QFrame(self.SocialQTBox)
        self.line_13.setGeometry(QtCore.QRect(9, 27, 657, 16))
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.toolBox.addItem(self.SocialQTBox, _fromUtf8(""))
        self.AnalysisQTBox = QtGui.QWidget()
        self.AnalysisQTBox.setGeometry(QtCore.QRect(0, 0, 675, 459))
        self.AnalysisQTBox.setObjectName(_fromUtf8("AnalysisQTBox"))
        self.GraphBtn = QtGui.QPushButton(self.AnalysisQTBox)
        self.GraphBtn.setGeometry(QtCore.QRect(570, 120, 90, 24))
        self.GraphBtn.setObjectName(_fromUtf8("GraphBtn"))
        self.LblGraphic = QtGui.QLabel(self.AnalysisQTBox)
        self.LblGraphic.setGeometry(QtCore.QRect(20, 170, 518, 251))
        self.LblGraphic.setAutoFillBackground(False)
        self.LblGraphic.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LblGraphic.setText(_fromUtf8(""))
        self.LblGraphic.setScaledContents(True)
        self.LblGraphic.setObjectName(_fromUtf8("LblGraphic"))
        self.RenderBtn = QtGui.QPushButton(self.AnalysisQTBox)
        self.RenderBtn.setGeometry(QtCore.QRect(570, 40, 90, 24))
        self.RenderBtn.setObjectName(_fromUtf8("RenderBtn"))
        self.line = QtGui.QFrame(self.AnalysisQTBox)
        self.line.setGeometry(QtCore.QRect(20, 90, 644, 21))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.LabelListFieldsCBox = QtGui.QComboBox(self.AnalysisQTBox)
        self.LabelListFieldsCBox.setGeometry(QtCore.QRect(107, 123, 419, 22))
        self.LabelListFieldsCBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.LabelListFieldsCBox.setObjectName(_fromUtf8("LabelListFieldsCBox"))
        self.label_3 = QtGui.QLabel(self.AnalysisQTBox)
        self.label_3.setGeometry(QtCore.QRect(22, 125, 64, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.AnlsBtnBox = QtGui.QDialogButtonBox(self.AnalysisQTBox)
        self.AnlsBtnBox.setGeometry(QtCore.QRect(565, 504, 86, 23))
        self.AnlsBtnBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel)
        self.AnlsBtnBox.setObjectName(_fromUtf8("AnlsBtnBox"))
        self.label_4 = QtGui.QLabel(self.AnalysisQTBox)
        self.label_4.setGeometry(QtCore.QRect(20, 40, 161, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.line_14 = QtGui.QFrame(self.AnalysisQTBox)
        self.line_14.setGeometry(QtCore.QRect(20, 10, 644, 21))
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.spinBoxClasNum = QtGui.QSpinBox(self.AnalysisQTBox)
        self.spinBoxClasNum.setGeometry(QtCore.QRect(360, 40, 42, 22))
        self.spinBoxClasNum.setProperty("value", 5)
        self.spinBoxClasNum.setObjectName(_fromUtf8("spinBoxClasNum"))
        self.label_7 = QtGui.QLabel(self.AnalysisQTBox)
        self.label_7.setGeometry(QtCore.QRect(230, 40, 111, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.toolBox.addItem(self.AnalysisQTBox, _fromUtf8(""))
        self.RulesQTBox = QtGui.QWidget()
        self.RulesQTBox.setGeometry(QtCore.QRect(0, 0, 675, 459))
        self.RulesQTBox.setObjectName(_fromUtf8("RulesQTBox"))
        self.CritExtractBtn = QtGui.QPushButton(self.RulesQTBox)
        self.CritExtractBtn.setGeometry(QtCore.QRect(520, 10, 141, 31))
        self.CritExtractBtn.setObjectName(_fromUtf8("CritExtractBtn"))
        self.RulesListWidget = QtGui.QListWidget(self.RulesQTBox)
        self.RulesListWidget.setGeometry(QtCore.QRect(10, 60, 651, 291))
        self.RulesListWidget.setObjectName(_fromUtf8("RulesListWidget"))
        self.SaveRulesBtn = QtGui.QPushButton(self.RulesQTBox)
        self.SaveRulesBtn.setGeometry(QtCore.QRect(580, 360, 81, 31))
        self.SaveRulesBtn.setObjectName(_fromUtf8("SaveRulesBtn"))
        self.groupBox_3 = QtGui.QGroupBox(self.RulesQTBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 400, 651, 51))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.baseLbl = QtGui.QLabel(self.groupBox_3)
        self.baseLbl.setGeometry(QtCore.QRect(20, 20, 621, 21))
        self.baseLbl.setObjectName(_fromUtf8("baseLbl"))
        self.EnvRadioBtn = QtGui.QRadioButton(self.RulesQTBox)
        self.EnvRadioBtn.setGeometry(QtCore.QRect(10, 10, 131, 21))
        self.EnvRadioBtn.setChecked(True)
        self.EnvRadioBtn.setObjectName(_fromUtf8("EnvRadioBtn"))
        self.EcoRadioBtn = QtGui.QRadioButton(self.RulesQTBox)
        self.EcoRadioBtn.setGeometry(QtCore.QRect(200, 10, 111, 21))
        self.EcoRadioBtn.setObjectName(_fromUtf8("EcoRadioBtn"))
        self.SocRadioBtn = QtGui.QRadioButton(self.RulesQTBox)
        self.SocRadioBtn.setGeometry(QtCore.QRect(370, 10, 101, 21))
        self.SocRadioBtn.setObjectName(_fromUtf8("SocRadioBtn"))
        self.toolBox.addItem(self.RulesQTBox, _fromUtf8(""))
        self.gridLayout.addWidget(self.toolBox, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.toolBox.setCurrentIndex(5)
        self.toolBox.layout().setSpacing(6)
        self.EnvTabWidget.setCurrentIndex(0)
        self.EcoTabWidget.setCurrentIndex(0)
        self.SocTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.EnvAddFieldBtn, self.EnvRemoveFieldBtn)
        Dialog.setTabOrder(self.EnvRemoveFieldBtn, self.EnvTEdit)
        Dialog.setTabOrder(self.EnvTEdit, self.GraphBtn)
        Dialog.setTabOrder(self.GraphBtn, self.OutlEdt)
        Dialog.setTabOrder(self.OutlEdt, self.RetriveFileTBtn)
        Dialog.setTabOrder(self.RetriveFileTBtn, self.SetBtnBox)
        Dialog.setTabOrder(self.SetBtnBox, self.SetBtnHelp)
        Dialog.setTabOrder(self.SetBtnHelp, self.SetBtnAbout)
        Dialog.setTabOrder(self.SetBtnAbout, self.EnvHelpBtn)
        Dialog.setTabOrder(self.EnvHelpBtn, self.EcolistFieldsCBox)
        Dialog.setTabOrder(self.EcolistFieldsCBox, self.EcoTEdit)
        Dialog.setTabOrder(self.EcoTEdit, self.EcoHelpBtn)
        Dialog.setTabOrder(self.EcoHelpBtn, self.EcoRemoveFieldBtn)
        Dialog.setTabOrder(self.EcoRemoveFieldBtn, self.EcoAddFieldBtn)
        Dialog.setTabOrder(self.EcoAddFieldBtn, self.EnvlistFieldsCBox)
        Dialog.setTabOrder(self.EnvlistFieldsCBox, self.RenderBtn)
        Dialog.setTabOrder(self.RenderBtn, self.LabelListFieldsCBox)
        Dialog.setTabOrder(self.LabelListFieldsCBox, self.AnlsBtnBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "geoSUIT - Geographic UmbriaSUIT ", None))
        self.OutGBox.setTitle(_translate("Dialog", "Output file", None))
        self.RetriveFileTBtn.setText(_translate("Dialog", "...", None))
        self.groupBox.setTitle(_translate("Dialog", "Configure", None))
        self.settingCheckBox.setText(_translate("Dialog", " Use setting file (setting.csv)", None))
        self.prefixECOlEdt.setText(_translate("Dialog", "E_", None))
        self.label_2.setText(_translate("Dialog", "Economic prefix", None))
        self.label.setText(_translate("Dialog", "Environmental  prefix", None))
        self.preFIXcheckBox.setText(_translate("Dialog", "use prefix for criteria", None))
        self.label_5.setText(_translate("Dialog", "Social prefix", None))
        self.prefixSOClEdt.setText(_translate("Dialog", "S_", None))
        self.prefixENVlEdt.setText(_translate("Dialog", "A_", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Base layer", None))
        self.BaseLayerLbl.setText(_translate("Dialog", "TextLabel", None))
        self.SetBtnHelp.setText(_translate("Dialog", "Help", None))
        self.SetBtnAbout.setText(_translate("Dialog", "About", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Dialog", "Setting", None))
        self.EnvLbl.setText(_translate("Dialog", "Layer     ", None))
        self.EnvFieldsLbl.setText(_translate("Dialog", "Fields", None))
        self.EnvHelpBtn.setText(_translate("Dialog", "Help", None))
        self.EnvGetWeightBtn.setText(_translate("Dialog", "Apply", None))
        self.EnvSaveCfgBtn.setText(_translate("Dialog", "Save", None))
        self.EnvTabWidget.setTabText(self.EnvTabWidget.indexOf(self.tab_5), _translate("Dialog", "Standard", None))
        self.EnvCalculateBtn.setText(_translate("Dialog", "Calculate weight", None))
        self.EnvTabWidget.setTabText(self.EnvTabWidget.indexOf(self.tab_6), _translate("Dialog", "Advanced", None))
        self.EnvTabWidget.setTabToolTip(self.EnvTabWidget.indexOf(self.tab_6), _translate("Dialog", "<html><head/><body><p><br/></p><p>colun vs row </p><p><br/></p></body></html>", None))
        self.EnvRemoveFieldBtn.setText(_translate("Dialog", "Remove", None))
        self.EnvAddFieldBtn.setText(_translate("Dialog", "Add", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.EnvironmentaleQTbox), _translate("Dialog", "Environmental criteria", None))
        self.EcoFieldsLbl.setText(_translate("Dialog", "Fields", None))
        self.EcoLbl.setText(_translate("Dialog", "Layer     ", None))
        self.EcoHelpBtn.setText(_translate("Dialog", "Help", None))
        self.EcoRemoveFieldBtn.setText(_translate("Dialog", "Remove", None))
        self.EcoAddFieldBtn.setText(_translate("Dialog", "Add", None))
        self.EcoGetWeightBtn.setText(_translate("Dialog", "Apply", None))
        self.EcoSaveCfgBtn.setText(_translate("Dialog", "Save", None))
        self.EcoTabWidget.setTabText(self.EcoTabWidget.indexOf(self.tab_3), _translate("Dialog", "Standard", None))
        self.EcoCalculateBtn.setText(_translate("Dialog", "Calculate weight", None))
        self.EcoTabWidget.setTabText(self.EcoTabWidget.indexOf(self.tab_4), _translate("Dialog", "Advanced", None))
        self.EcoTabWidget.setTabToolTip(self.EcoTabWidget.indexOf(self.tab_4), _translate("Dialog", "<html><head/><body><p><br/></p><p>colun vs row </p><p><br/></p></body></html>", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.EconomicsQTBox), _translate("Dialog", "Economic criteria", None))
        self.SocGetWeightBtn.setText(_translate("Dialog", "Apply", None))
        self.SocSaveCfgBtn.setText(_translate("Dialog", "Save", None))
        self.SocTabWidget.setTabText(self.SocTabWidget.indexOf(self.tab_7), _translate("Dialog", "Standard", None))
        self.SocCalculateBtn.setText(_translate("Dialog", "Calculate weight", None))
        self.SocTabWidget.setTabText(self.SocTabWidget.indexOf(self.tab_8), _translate("Dialog", "Advanced", None))
        self.SocTabWidget.setTabToolTip(self.SocTabWidget.indexOf(self.tab_8), _translate("Dialog", "<html><head/><body><p><br/></p><p>colun vs row </p><p><br/></p><p><br/></p></body></html>", None))
        self.SocAddFieldBtn.setText(_translate("Dialog", "Add", None))
        self.SocRemoveFieldBtn.setText(_translate("Dialog", "Remove", None))
        self.SocFieldsLbl.setText(_translate("Dialog", "Fields", None))
        self.SocHelpBtn.setText(_translate("Dialog", "Help", None))
        self.EcoLbl_2.setText(_translate("Dialog", "Layer     ", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.SocialQTBox), _translate("Dialog", "Social criteria ", None))
        self.GraphBtn.setText(_translate("Dialog", "Graph", None))
        self.RenderBtn.setText(_translate("Dialog", "Load maps", None))
        self.label_3.setText(_translate("Dialog", "Label field", None))
        self.label_4.setText(_translate("Dialog", "Load thematic maps", None))
        self.label_7.setText(_translate("Dialog", "Classes in maps", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.AnalysisQTBox), _translate("Dialog", "Analysis", None))
        self.CritExtractBtn.setText(_translate("Dialog", " Extract rules", None))
        self.SaveRulesBtn.setText(_translate("Dialog", "Save rules", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Active layer", None))
        self.baseLbl.setText(_translate("Dialog", "TextLabel", None))
        self.EnvRadioBtn.setText(_translate("Dialog", "Environment rules", None))
        self.EcoRadioBtn.setText(_translate("Dialog", "Economic rules", None))
        self.SocRadioBtn.setText(_translate("Dialog", "Social rules", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.RulesQTBox), _translate("Dialog", "Rules", None))

